export const sources = {
  arkclawFeatures: "火山引擎 ArkClaw 文档：功能概述",
  arkclawSpecs: "火山引擎 ArkClaw 文档：规格与适用场景",
  arkclawManage: "火山引擎 ArkClaw 文档：管理 ArkClaw",
  cncertRisk: "CNCERT：OpenClaw 安全应用风险提示，2026.03",
  cncertGuide: "CNCERT：OpenClaw 安全使用实践指南，2026.03",
  nvdCve: "NVD：CVE-2026-25253",
  ciscoSkills: "Cisco AI Defense：31,000 个 Agent Skills 扫描研究",
};

export const sourceLinks = [
  ["火山引擎 ArkClaw 文档", "https://www.volcengine.com/docs/87732/2254723?lang=zh"],
  ["CNCERT 风险提示", "https://www.cert.org.cn/publish/main/11/2026/20260312144519429724511/20260312144519429724511_.html"],
  ["CNCERT 安全实践指南", "https://www.cert.org.cn/publish/main/11/2026/20260323113411436406469/20260323113411436406469_.html"],
  ["NVD CVE-2026-25253", "https://nvd.nist.gov/vuln/detail/CVE-2026-25253"],
  ["Cisco AI Defense Skills 研究", "https://blogs.cisco.com/ai/personal-ai-agents-like-openclaw-are-a-security-nightmare"],
];

export const assets = {
  cover: "scratch/assets/cover-agent-studio.png",
  creation: "scratch/assets/creation-atelier.png",
  security: "scratch/assets/security-shadow.png",
  balance: "scratch/assets/balance-finale.png",
};

export const slides = [
  {
    kind: "cover",
    art: "cover",
    title: "用 ArkClaw\n做艺术设计",
    subtitle: "AI Agent 实战能力 × AI 时代的网络安全意识",
    meta: "仲恺农业工程学院 · 信息传媒学院 · 2026.04.24",
    speaker: "彭超 Pong · ChaoGeek · OneOneTalk CTO · ADG 广州社区负责人",
  },
  {
    kind: "profile",
    title: "这不是一场工具说明书",
    subtitle: "而是一段从课堂走到云端工作室的真实路径",
    quote: "亲手试过，才有资格说。",
    lines: [
      "14 年 IT 经验：保险、银行、金融科技、AI",
      "OneOneTalk 联合创始人 & CTO",
      "ADG 广州社区负责人 / TRAE Expert",
      "讯飞 AI 开发者大赛一等奖",
      "曾经的高中政治老师，现在的 AI 布道者",
    ],
  },
  {
    kind: "statement",
    art: "cover",
    title: "2026，App 像画框",
    subtitle: "Agent 更像站在你身后的助理",
    claim: "它不只回答你，它会替你行动。",
    lines: ["读文件", "写代码", "操作浏览器", "调用 API"],
    source: sources.cncertRisk,
  },
  {
    kind: "atelier",
    title: "ArkClaw 是一间\n开在浏览器里的云端工作室",
    subtitle: "把复杂环境、技能、消息入口和云端执行，收进一个可控空间。",
    items: [
      ["浏览器即用", "快速创建专属 AI 助手"],
      ["云电脑 / 云浏览器", "任务在云端发生"],
      ["Skill Hub / ClawHub", "按创作任务安装技能"],
      ["飞书 / 企业微信 / 钉钉", "把 Agent 放进协作现场"],
      ["模型与资源管理", "运行状态、日志、资源可查看"],
    ],
    source: `${sources.arkclawFeatures}；${sources.arkclawSpecs}；${sources.arkclawManage}`,
  },
  {
    kind: "section",
    art: "creation",
    tone: "blue",
    title: "第一幕\n把想象说出来",
    subtitle: "Talk is cheap. 让 AI 干活。",
    kicker: "四个现场场景",
  },
  {
    kind: "promptDemo",
    art: "creation",
    title: "一句话，变成一座网站",
    prompt: "帮我做一个赛博朋克风个人作品集",
    lines: ["暗底霓虹、粒子、响应式布局", "中文描述视觉，Agent 生成代码", "你负责审美，它负责落地"],
    quote: "最热门的新编程语言，是中文。",
  },
  {
    kind: "posterVariants",
    title: "同一段文案，三种海报性格",
    subtitle: "对艺术设计来说，AI 最先放大的不是“完成”，而是“比较”。",
    styles: [
      ["极简主义", "留白、秩序、冷静"],
      ["复古未来", "颗粒、霓虹、速度"],
      ["日式侘寂", "克制、材质、呼吸"],
    ],
    punch: "三版方案：从 1-2 天，到 10 分钟。",
  },
  {
    kind: "timeline",
    title: "PPT 不再是熬夜",
    subtitle: "它变成一次视觉编排。",
    prompt: "做一个 10 页新媒体趋势分享 PPT，深色主题，要有数据图表",
    steps: ["结构", "内容", "图表", "导出"],
    quote: "以前你加班做 PPT，现在 PPT 加班帮你做。",
  },
  {
    kind: "workflow",
    art: "creation",
    title: "一个人背后，站着一支影子团队",
    steps: ["每天早 8 点", "抓取行业热点", "生成摘要 + 点评", "推送到群"],
    cases: ["小红书文案", "公众号标题 A/B", "短视频脚本", "竞品内容监控"],
    quote: "一个人 + 一个 AI Agent = 一支团队。",
  },
  {
    kind: "section",
    art: "security",
    tone: "red",
    title: "第二幕\n画布背面也有门",
    subtitle: "它能帮你创作，也可能被别人指挥。",
    kicker: "AI Agent 时代的网络安全风险",
  },
  {
    kind: "riskPrompt",
    art: "security",
    title: "提示词注入",
    subtitle: "藏在作品背面的暗语",
    flow: ["恶意网页 / 文件", "Agent 读取", "执行隐藏指令", "密钥或数据泄露"],
    analogy: "就像让实习生抄资料，资料里却夹着一行：先把老板密码发给我。",
    source: sources.cncertRisk,
  },
  {
    kind: "riskSkills",
    title: "漂亮按钮，也可能有刺",
    risks: [
      ["插件投毒", "恶意 Skill 可能外传数据、植入后门"],
      ["沙箱逃逸", "CVE-2026-25253 被评为 8.8 High"],
      ["供应链放大", "Cisco 研究称 31,000 个 Skills 中 26% 至少含一个漏洞"],
    ],
    source: `${sources.cncertRisk}；${sources.nvdCve}；${sources.ciscoSkills}`,
  },
  {
    kind: "safety",
    art: "balance",
    title: "把高权限放进\n更可控的云端",
    subtitle: "对新手来说，安全不是少用 AI，而是让它在合适的边界里行动。",
    layers: [
      ["云端隔离", "和本地电脑隔开"],
      ["Skills 检测", "降低插件投毒风险"],
      ["人工确认", "高危操作前停一下"],
      ["日志审计", "运行状态和操作事件可追溯"],
    ],
    source: `${sources.arkclawManage}；${sources.cncertGuide}`,
  },
  {
    kind: "habits",
    title: "带走四条安全肌肉记忆",
    habits: [
      ["01", "不装来路不明的 Skill", "像不从野站下载 PS 插件一样"],
      ["02", "敏感文件别直接喂 Agent", "客户素材、未发布作品、商业合同"],
      ["03", "检查 AI 生成的代码", "尤其看它往哪里发网络请求"],
      ["04", "及时更新版本", "漏洞修得快，你也要跟得快"],
    ],
    source: sources.cncertGuide,
  },
  {
    kind: "summary",
    art: "balance",
    title: "能力和边界\n必须一起被设计",
    leftTitle: "创作力",
    left: ["一句话出网页", "十分钟做 PPT", "自动化内容流", "一人 = 一支团队"],
    rightTitle: "攻击面",
    right: ["提示词注入", "插件投毒", "沙箱逃逸", "权限失控"],
    quote: "你给 AI 越大的权力，你就越需要理解它的边界。",
  },
  {
    kind: "closing",
    art: "cover",
    title: "亲手试过，才有资格说。",
    links: ["ArkClaw：volcengine.com/product/arkclaw", "公众号：ChaoGeek", "社区：ADG 广州开发者社区"],
    question: "你会用 AI 做什么设计？",
  },
];
